import { useEffect } from 'react';
import {
  Links,
  Meta,
  Outlet,
  Scripts,
  ScrollRestoration,
  type LinksFunction,
} from 'react-router';

/*
 * The fonts are SELF-HOSTED, and that is a performance decision before it is a
 * privacy one. They used to come from Google: a render-blocking stylesheet on
 * fonts.googleapis.com, which the browser had to fetch (DNS + TLS + request) before
 * it even learned that the actual woff2 lived on a SECOND origin, fonts.gstatic.com.
 * Two full round trips against two new origins, all of it standing between the
 * visitor and the first pixel — 4.6s to first paint on a throttled phone, with zero
 * blocking JavaScript. The site was not slow; it was waiting for Google.
 *
 * It also settles a contradiction: /colophon promises no tracking, while every
 * visitor's IP went to Google twice just to render the text saying so.
 */
import themeStylesheetUrl from '@dev-blog/theme/styles/tailwind.css?url';
import {
  ACCENT_STORAGE_KEY,
  ACCENTS,
  Button,
  Link,
  RouteErrorBoundary,
} from '@dev-blog/ui';

import { SiteFooter } from './components/site-footer';
import { SiteHeader } from './components/site-header';
import { useNonce } from './lib/nonce';
import { seoMeta } from './lib/seo';
import { SITE_NAME, SITE_URL } from './lib/site';

export function loader() {
  return { origin: SITE_URL };
}

export const meta = ({
  loaderData,
  location,
}: {
  loaderData?: ReturnType<typeof loader>;
  location: { pathname: string };
}) =>
  seoMeta({
    origin: loaderData?.origin ?? SITE_URL,
    path: location.pathname,
    title: `${SITE_NAME} — software, systems and decisions`,
    description: 'Notes on architecture, tooling and developer experience.',
  });

export const links: LinksFunction = () => [
  { rel: 'icon', type: 'image/svg+xml', href: '/favicon.svg' },
  /*
   * iOS does NOT fall back to the favicon. Without this file, "Add to Home Screen"
   * uses a SCREENSHOT of the page — on a dark site, an unreadable black rectangle.
   * Generated by tools/app-icons.mjs; square and full-bleed, because iOS applies its
   * own corner mask and would fill a pre-rounded icon's corners with black.
   */
  { rel: 'apple-touch-icon', sizes: '180x180', href: '/apple-touch-icon.png' },
  /*
   * Only the SANS is preloaded, and only because it paints the headings. The mono
   * face is deliberately NOT: it dresses small labels, and a preload is a
   * high-priority fetch that would compete for bandwidth with the stylesheet standing
   * between the visitor and the first pixel. Preloading everything preloads nothing —
   * measured: preloading both cost ~0.3s of LCP against preloading just this one.
   *
   * crossOrigin is required on a font preload even same-origin, or the file is
   * fetched twice. The @font-face lives in libs/theme/src/styles/fonts.css.
   */
  {
    rel: 'preload',
    as: 'font',
    type: 'font/woff2',
    href: '/fonts/space-grotesk-latin-wght-normal.woff2',
    crossOrigin: 'anonymous',
  },
  { rel: 'stylesheet', href: themeStylesheetUrl },
  {
    rel: 'alternate',
    type: 'application/rss+xml',
    title: SITE_NAME,
    href: '/rss.xml',
  },
];

/*
 * Applies the visitor's saved accent BEFORE the first paint.
 *
 * The server cannot know it. It is in localStorage — not a cookie, because /colophon
 * promises there are none, and a promise the site quietly breaks is worse than a
 * feature it does not have. So the HTML always leaves the server saying `yellow`, and
 * without this script the page painted yellow and only became lime once React had
 * hydrated: a visible flash, on every page, for anyone who ever changed the accent.
 *
 * It is inline and synchronous on purpose — that is what makes it run before the body
 * is painted. A deferred or external script is too late by definition.
 *
 * The key and the names come from the design system, not from a copy: two spellings of
 * 'fabio-accent' would be one rename away from a silent bug.
 */
const APPLY_SAVED_ACCENT = `try{var a=localStorage.getItem(${JSON.stringify(
  ACCENT_STORAGE_KEY,
)});if(${JSON.stringify([
  ...ACCENTS,
])}.indexOf(a)>0)document.documentElement.dataset.accent=a}catch(e){}`;

export function Layout({ children }: { children: React.ReactNode }) {
  const nonce = useNonce();

  return (
    <html lang="en" data-accent="yellow">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/*
          Paints the browser chrome (Android Chrome's bar, Safari's toolbar) with our
          background instead of system white. Hex, not the oklch token: this value is
          read by the OS shell, not by our stylesheet. It is --color-neutral-950.
        */}
        <meta name="theme-color" content="#121921" />
        <meta name="color-scheme" content="dark" />
        {/* Carries the response's nonce: the CSP allows no other inline script. */}
        <script
          nonce={nonce}
          dangerouslySetInnerHTML={{ __html: APPLY_SAVED_ACCENT }}
        />
        <Meta />
        <Links />
      </head>
      <body>
        <div className="flex min-h-screen flex-col">
          <SiteHeader />
          <div id="content" className="flex flex-1 flex-col">
            {children}
          </div>
          <SiteFooter />
        </div>
        <ScrollRestoration />
        <Scripts />
      </body>
    </html>
  );
}

export default function App() {
  /*
   * Mark the document hydrated once React has taken over on the client. The SSR
   * HTML ships without it, so a test can wait for interactivity deterministically
   * instead of racing it: an e2e click that lands before hydration hits markup
   * with no handler attached, does nothing, and the assertion times out — which
   * is what made the accent spec flake, but only on a cold server. Inert in
   * production; nothing reads it but the tests.
   */
  useEffect(() => {
    document.documentElement.dataset['hydrated'] = 'true';
  }, []);

  return <Outlet />;
}

export function ErrorBoundary() {
  return (
    <RouteErrorBoundary
      notFound={{
        prompt: (
          <>
            $ curl fabiomenchicchi.com/this-page{' '}
            <span className="text-primary">→ HTTP 404</span>
          </>
        ),
        title: 'Page not found',
        description:
          "The URL you're looking for doesn't exist — or I deleted it. Deleting code is an art form; deleting pages, an accident.",
        actions: (
          <Button asChild>
            <Link to="/" variant="plain">
              Back to the blog
            </Link>
          </Button>
        ),
      }}
      unexpected={{
        prompt: (
          <>
            $ tail -f /var/log/fabiomenchicchi.com{' '}
            <span className="text-primary">→ HTTP 500</span>
          </>
        ),
        title: 'Something broke',
        description:
          'A server-side error on my side, not yours. Try again in a moment; if it keeps happening, it is worth telling me.',
        actions: (
          <>
            <Button onClick={() => window.location.reload()}>
              Reload the page
            </Button>
            <Link
              to="/"
              variant="plain"
              className="font-mono text-xs text-muted-foreground no-underline [transition:var(--transition-color)] hover:text-primary"
            >
              ← or back to the blog
            </Link>
          </>
        ),
      }}
    />
  );
}
