/**
 * Inlines a mermaid diagram's committed SVG by its content hash.
 *
 * The SVG is inlined — not an <img> — so its token colours (`var(--color-primary)` and
 * friends) resolve against the page, and it follows the theme and the accent switch. The
 * SVGs are generated by
 * nx run blog:diagrams; a ```mermaid block becomes `<MermaidDiagram hash="…" />` via
 * remark-mermaid.
 *
 * Two folders, mirroring the drafts split: published diagrams always ship; a draft's ship
 * only on the dev server, gated on `MODE === 'development'` so the production build drops
 * the glob — a draft's diagram never reaches the bundle, exactly like its prose.
 */
function byHash(modules: Record<string, string>): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [path, svg] of Object.entries(modules)) {
    out[path.replace(/^.*\//, '').replace(/\.svg$/, '')] = svg;
  }
  return out;
}

const published = byHash(
  import.meta.glob('../diagrams/*.svg', {
    query: '?raw',
    import: 'default',
    eager: true,
  }) as Record<string, string>,
);

const draft =
  import.meta.env.MODE === 'development'
    ? byHash(
        import.meta.glob('../diagrams-draft/*.svg', {
          query: '?raw',
          import: 'default',
          eager: true,
        }) as Record<string, string>,
      )
    : {};

const svgs = { ...published, ...draft };

export function MermaidDiagram({ hash }: { hash: string }) {
  const svg = svgs[hash];

  if (!svg) {
    return (
      <figure className="my-7">
        <div className="rounded-xl border border-dashed border-border-strong bg-muted p-6 text-sm text-muted-foreground">
          Diagram <code>{hash}</code> has not been rendered yet — run{' '}
          <code>nx run blog:diagrams</code>.
        </div>
      </figure>
    );
  }

  return (
    <figure className="my-7">
      <div
        className="overflow-x-auto rounded-xl border border-border bg-card p-6 [&_svg]:mx-auto [&_svg]:h-auto [&_svg]:max-w-full"
        dangerouslySetInnerHTML={{ __html: svg }}
      />
    </figure>
  );
}
